name: daily-next

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
    - name: Set TAG_NAME
      run: | 
        echo "TAG_NAME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Clone build scripts
      uses: actions/checkout@v4

    - name: Build daily .iso
      run: |
        ./workflows.sh etc/terraform-daily-8.0-azure.conf "${{ secrets.key }}" "${{ secrets.secret }}" "${{ secrets.endpoint }}" "${{ secrets.bucket }}"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
         ./builds/amd64/*.iso
